
// This file has been generated by the GUI designer. Do not modify.
namespace Turing
{
	public partial class TuringDisplay
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.DrawingArea turingCode;

		private global::Gtk.Button nextStepBtn;

		private global::Gtk.Button runToEnd;

		private global::Gtk.Button showLog;

		private global::Gtk.ScrolledWindow turingAruaContainer;

		private global::Gtk.DrawingArea turingAria;

		private global::Gtk.Expander expander1;

		private global::Gtk.Label GtkLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Turing.TuringDisplay
			this.WidthRequest = 1400;
			this.HeightRequest = 800;
			this.Name = "Turing.TuringDisplay";
			this.Title = global::Mono.Unix.Catalog.GetString("TuringDisplay");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Turing.TuringDisplay.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.WidthRequest = 1390;
			this.scrolledwindow1.HeightRequest = 710;
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.turingCode = new global::Gtk.DrawingArea();
			this.turingCode.Name = "turingCode";
			w1.Add(this.turingCode);
			this.scrolledwindow1.Add(w1);
			this.fixed2.Add(this.scrolledwindow1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.scrolledwindow1]));
			w4.X = 5;
			w4.Y = 5;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.nextStepBtn = new global::Gtk.Button();
			this.nextStepBtn.CanFocus = true;
			this.nextStepBtn.Name = "nextStepBtn";
			this.nextStepBtn.UseUnderline = true;
			this.nextStepBtn.Label = global::Mono.Unix.Catalog.GetString("Наступний крок");
			this.fixed2.Add(this.nextStepBtn);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.nextStepBtn]));
			w5.X = 5;
			w5.Y = 720;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.runToEnd = new global::Gtk.Button();
			this.runToEnd.CanFocus = true;
			this.runToEnd.Name = "runToEnd";
			this.runToEnd.UseUnderline = true;
			this.runToEnd.Label = global::Mono.Unix.Catalog.GetString("Запустити до кінця без зупинок");
			this.fixed2.Add(this.runToEnd);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.runToEnd]));
			w6.X = 120;
			w6.Y = 720;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.showLog = new global::Gtk.Button();
			this.showLog.CanFocus = true;
			this.showLog.Name = "showLog";
			this.showLog.UseUnderline = true;
			this.showLog.Label = global::Mono.Unix.Catalog.GetString("Показати лог виконання программи");
			this.fixed2.Add(this.showLog);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.showLog]));
			w7.X = 330;
			w7.Y = 720;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.turingAruaContainer = new global::Gtk.ScrolledWindow();
			this.turingAruaContainer.WidthRequest = 1390;
			this.turingAruaContainer.HeightRequest = 35;
			this.turingAruaContainer.CanFocus = true;
			this.turingAruaContainer.Name = "turingAruaContainer";
			this.turingAruaContainer.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child turingAruaContainer.Gtk.Container+ContainerChild
			global::Gtk.Viewport w8 = new global::Gtk.Viewport();
			w8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.turingAria = new global::Gtk.DrawingArea();
			this.turingAria.Name = "turingAria";
			w8.Add(this.turingAria);
			this.turingAruaContainer.Add(w8);
			this.fixed2.Add(this.turingAruaContainer);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.turingAruaContainer]));
			w11.X = 5;
			w11.Y = 760;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.expander1 = new global::Gtk.Expander(null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.GtkLabel = new global::Gtk.Label();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel;
			this.fixed2.Add(this.expander1);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.expander1]));
			w12.X = 614;
			w12.Y = 144;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1400;
			this.DefaultHeight = 800;
			this.Show();
		}
	}
}
