
// This file has been generated by the GUI designer. Do not modify.
namespace Turing
{
	public partial class LogWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView logWindow;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Turing.LogWindow
			this.Name = "Turing.LogWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("LogWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Turing.LogWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.logWindow = new global::Gtk.TextView();
			this.logWindow.CanFocus = true;
			this.logWindow.Name = "logWindow";
			this.logWindow.Editable = false;
			this.GtkScrolledWindow.Add(this.logWindow);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
